services:
  mysql:
    image: mysql:8.0
    container_name: mysql_employee
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: technical_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - employee-network

  api:
    build: .
    container_name: msvc_employees
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/technical_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sasa
    depends_on:
      - mysql
    networks:
      - employee-network

volumes:
  mysql_data:

networks:
  employee-network:
