jwt:
  secret: FuE1iqwC6o8mBo9aTRDAMXvHEPA1BAC2jvEk19gyLoU=
  expiration: 3600
spring:

  application:
    name: msvc-employees

  server:
    port: 8080

  datasource:
    url: jdbc:mysql://localhost:3306/technical_test?useSSL=false&serverTimezone=UTC
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: America/Mexico_City
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

  logging:
    level:
      root: INFO
      com.example: DEBUG
      org.springframework.web: DEBUG

  management:
    endpoints:
      web:
        exposure:
          include: health,info

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html