jwt:
  secret: FuE1iqwC6o8mBo9aTRDAMXvHEPA1BAC2jvEk19gyLoU=
  expiration: 3600

spring:

  application:
    name: msvc-employees

  server:
    port: 8080

  datasource:
    url: jdbc:mysql://localhost:3306/technical_test?useSSL=false&serverTimezone=UTC
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: America/Mexico_City
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher


  management:
    endpoints:
      web:
        exposure:
          include: "*"

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
      display-request-duration: true

logging:
  level:
    root: INFO
    com.david.employee: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
  file:
    name: logs/employee-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

info:
  app:
    name: Microservice Employee Management
    description: API for managing employees
    version: 1.0.0