openapi: 3.0.3
info:
  title: MSVC Employees API
  version: 1.0.0
  description: Microservice API for managing employees, with JWT authentication and role-based access control.

servers:
  - url: http://localhost:8080

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequestDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    EmployeeResponseDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        lastName:
          type: string
        role:
          type: string

    CreateEmployeeRequestDto:
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        role:
          type: string
      required:
        - name
        - lastName
        - birthDate
        - role

    UpdateEmployeeRequestDto:
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        role:
          type: string

    BatchCreationResultDto:
      type: object
      properties:
        successful:
          type: array
          items:
            $ref: '#/components/schemas/EmployeeResponseDto'
        failed:
          type: array
          items:
            $ref: '#/components/schemas/EmployeeResponseDto'

    GlobalResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object

paths:
  /api/auth/login:
    post:
      summary: User login
      description: Authenticates a user with username and password, returns a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDto'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'

  /api/employees:
    get:
      summary: Get all employees
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Employees retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: No employees found

    post:
      summary: Create employees
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateEmployeeRequestDto'
      responses:
        '201':
          description: Employees created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '409':
          description: Conflict. No employees were created

  /api/employees/{id}:
    get:
      summary: Get employee by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Employee retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Employee not found

    put:
      summary: Update employee
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmployeeRequestDto'
      responses:
        '200':
          description: Employee updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Employee not found

    delete:
      summary: Delete employee
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Employee deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Employee not found

  /api/employees/search:
    get:
      summary: Search employees by name
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Employees retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: No employees found with the provided name
